"""Windows certificate store signing, exercised against the real CNG stack.

The signer under test is the engine's own ``store_cert`` source, so what runs
is ``NCryptSignHash`` against a key handle Windows owns — no stub sits between
the assertion and the platform. The certificate is generated by the test,
imported into the CURRENT USER's ``MY`` store under a distinctive friendly
name, and removed in teardown (the SoftHSM precedent for real-stack testing).

The skip tests the CAPABILITY: a platform with no certificate store, not a
missing directory.
"""

import os

import pytest

import win_store
from engine import wincert
from engine.signatures import sign_pdf, verify_signatures

pytestmark = pytest.mark.skipif(
    not win_store.available(),
    reason="capability axis: no Windows certificate store on this machine",
)


def _identity(tmp_path_factory, key: str):
    """A throwaway store identity: (thumbprint,), removed when the test ends."""
    work = tmp_path_factory.mktemp("store")
    pfx = str(work / f"{key}.pfx")
    thumbprint = win_store.make_pfx(pfx, "test-passphrase", key=key)
    win_store.import_pfx(pfx, "test-passphrase")
    try:
        yield thumbprint
    finally:
        win_store.delete(thumbprint)


@pytest.fixture(scope="module")
def rsa_cert(tmp_path_factory):
    yield from _identity(tmp_path_factory, "rsa")


@pytest.fixture(scope="module")
def ec_cert(tmp_path_factory):
    yield from _identity(tmp_path_factory, "ec")


class TestStoreSign:
    def test_signs_and_self_verifies(self, rsa_cert, tmp_dir, sample_pdf):
        out = os.path.join(tmp_dir, "signed.pdf")
        r = sign_pdf(sample_pdf, out, store_cert=rsa_cert, reason="store-sign pytest")
        assert r["valid"] and r["intact"] and r["covers_whole_document"]
        assert r["signer"] == win_store.TEST_COMMON_NAME
        v = verify_signatures(out)
        assert v["signed"] and v["signatures"][0]["valid"] and v["signatures"][0]["intact"]

    def test_an_ec_key_signs(self, ec_cert, tmp_dir, sample_pdf):
        # ECDSA comes back from CNG as fixed-width r||s; a signature that
        # verifies proves the DER re-encoding, which nothing else exercises.
        out = os.path.join(tmp_dir, "ec.pdf")
        r = sign_pdf(sample_pdf, out, store_cert=ec_cert)
        assert r["valid"] and r["intact"]
        assert verify_signatures(out)["signatures"][0]["valid"]

    def test_pss_padding_is_the_declared_one(self, rsa_cert, tmp_dir, sample_pdf):
        # The salt length rides the mechanism the CMS declares, not a constant:
        # signing with any other salt produces a signature that verifies
        # against nothing while every other field still reads correct.
        import engine.signatures as sig_module

        class PssSigner(sig_module.StoreSigner):
            def __init__(self, handle, **kwargs):
                super().__init__(handle, prefer_pss=True)

        original = sig_module.StoreSigner
        sig_module.StoreSigner = PssSigner
        try:
            out = os.path.join(tmp_dir, "pss.pdf")
            r = sign_pdf(sample_pdf, out, store_cert=rsa_cert)
        finally:
            sig_module.StoreSigner = original
        assert r["valid"] and r["intact"]
        assert verify_signatures(out)["signatures"][0]["valid"]

    def test_visible_stamp_through_the_store(self, rsa_cert, tmp_dir, sample_pdf):
        out = os.path.join(tmp_dir, "visible.pdf")
        r = sign_pdf(
            sample_pdf, out, store_cert=rsa_cert,
            appearance={"page": 1, "rect": [100, 100, 300, 160]},
        )
        assert r["valid"] and r["intact"]

    def test_certification_through_the_store(self, rsa_cert, tmp_dir, sample_pdf):
        out = os.path.join(tmp_dir, "certified.pdf")
        r = sign_pdf(sample_pdf, out, store_cert=rsa_cert, certify=True, certify_level="form-fill")
        assert r["valid"] and r["certified"]
        assert r["certification_level"] == "form-fill"

    def test_field_lock_through_the_store(self, rsa_cert, tmp_dir, sample_pdf):
        out = os.path.join(tmp_dir, "locked.pdf")
        r = sign_pdf(sample_pdf, out, store_cert=rsa_cert, lock="all")
        assert r["valid"] and r["lock"] == "all"

    def test_in_place_signing_through_the_store(self, rsa_cert, tmp_dir, sample_pdf):
        import shutil

        target = os.path.join(tmp_dir, "in-place.pdf")
        shutil.copyfile(sample_pdf, target)
        r = sign_pdf(target, target, store_cert=rsa_cert, allow_in_place=True)
        assert r["valid"] and r["intact"]
        assert verify_signatures(target)["signature_count"] == 1

    def test_counter_signing_rotates_the_field_name(self, rsa_cert, tmp_dir, sample_pdf):
        first = os.path.join(tmp_dir, "one.pdf")
        second = os.path.join(tmp_dir, "two.pdf")
        sign_pdf(sample_pdf, first, store_cert=rsa_cert)
        r = sign_pdf(first, second, store_cert=rsa_cert)
        assert r["field"] == "Signature2"
        assert verify_signatures(second)["signature_count"] == 2

    def test_chain_material_comes_from_the_store(self, rsa_cert):
        # The chain engine's own answer, so the DSS and AIA behaviour matches
        # the file-based sources. A self-signed identity contributes no
        # issuers, which is a chain of length zero, not a failure.
        with wincert.StoreCertificate(rsa_cert) as handle:
            assert handle.certificate
            assert isinstance(handle.chain, list)
            assert handle.uses_cng


class TestStoreRefusals:
    def test_an_unknown_thumbprint_is_named(self, tmp_dir, sample_pdf):
        with pytest.raises(ValueError, match="No certificate with that thumbprint"):
            sign_pdf(
                sample_pdf, os.path.join(tmp_dir, "no.pdf"),
                store_cert="0" * 40,
            )

    def test_a_malformed_thumbprint_is_named(self, tmp_dir, sample_pdf):
        with pytest.raises(ValueError, match="40 hexadecimal characters"):
            sign_pdf(sample_pdf, os.path.join(tmp_dir, "no.pdf"), store_cert="not-a-thumbprint")

    def test_mixed_sources_refused(self, rsa_cert, tmp_dir, sample_pdf):
        with pytest.raises(ValueError, match="ONE signer source"):
            sign_pdf(
                sample_pdf, os.path.join(tmp_dir, "no.pdf"),
                pfx_path="x.pfx", store_cert=rsa_cert,
            )

    def test_an_unavailable_store_refuses_by_name(self, monkeypatch, tmp_dir, sample_pdf):
        monkeypatch.setattr(wincert, "available", lambda: False)
        with pytest.raises(ValueError, match="certificate store is not available"):
            sign_pdf(sample_pdf, os.path.join(tmp_dir, "no.pdf"), store_cert="0" * 40)

    def test_a_cancelled_prompt_is_a_refusal_not_a_failure(
        self, rsa_cert, tmp_dir, sample_pdf
    ):
        # Windows raises the consent UI itself and no test can click it, so the
        # cancellation is injected at the one place it can arrive. What is
        # under test is the CLASSIFICATION: the user's answer leaves through
        # the same refusal door every other signing refusal uses.
        def _cancel(*_args, **_kwargs):
            raise wincert.SigningCancelled()

        original = wincert.StoreCertificate.sign_digest
        wincert.StoreCertificate.sign_digest = _cancel
        try:
            with pytest.raises(ValueError, match="Signing was cancelled"):
                sign_pdf(sample_pdf, os.path.join(tmp_dir, "no.pdf"), store_cert=rsa_cert)
        finally:
            wincert.StoreCertificate.sign_digest = original

    def test_no_output_survives_a_refused_sign(self, tmp_dir, sample_pdf):
        out = os.path.join(tmp_dir, "never.pdf")
        with pytest.raises(ValueError):
            sign_pdf(sample_pdf, out, store_cert="0" * 40)
        assert not os.path.exists(out)


class TestThumbprintNormalization:
    @pytest.mark.parametrize(
        "spelling",
        ["AA BB CC" + "0" * 34, "aa:bb:cc" + "0" * 34, "AABBCC" + "0" * 34],
    )
    def test_spacing_and_case_are_accepted(self, spelling):
        # The store's own display spells a thumbprint with spaces and the
        # certificate dialog with none; both are the same identifier.
        assert wincert._normalized_thumbprint(spelling) == bytes.fromhex("AABBCC" + "0" * 34)

    @pytest.mark.parametrize("bad", ["", "zz", "0" * 39, "0" * 41, "g" * 40])
    def test_anything_else_is_refused(self, bad):
        with pytest.raises(ValueError, match="40 hexadecimal characters"):
            wincert._normalized_thumbprint(bad)


class TestEcdsaDer:
    def test_a_fixed_width_pair_becomes_a_der_sequence(self):
        raw = bytes([0x01] * 32) + bytes([0x02] * 32)
        der = wincert.ecdsa_der(raw)
        assert der[0] == 0x30
        assert len(der) == der[1] + 2

    def test_a_high_bit_integer_keeps_its_leading_zero(self):
        # DER INTEGER is signed: a value whose top bit is set needs a leading
        # zero byte, and omitting it makes the signature read as negative.
        raw = bytes([0xFF] * 32) + bytes([0x01] * 32)
        der = wincert.ecdsa_der(raw)
        assert der[2] == 0x02 and der[3] == 33 and der[4] == 0x00

    def test_an_odd_length_signature_is_refused(self):
        with pytest.raises(ValueError, match="malformed ECDSA signature"):
            wincert.ecdsa_der(bytes(31))

    @staticmethod
    def _decoded(raw: bytes):
        from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

        der = wincert.ecdsa_der(raw)
        half = len(raw) // 2
        r, s = decode_dss_signature(der)
        assert r == int.from_bytes(raw[:half], "big")
        assert s == int.from_bytes(raw[half:], "big")
        return der

    def test_a_p521_pair_decodes(self):
        # 66-byte halves: the payload passes 127 bytes, so the SEQUENCE length
        # must take DER's long form. Written short, the sequence claims a
        # truncated body and no parser accepts it.
        der = self._decoded(bytes([0x01] * 66) + bytes([0x02] * 66))
        assert der[:2] == b"\x30\x81"

    def test_a_p521_pair_at_maximum_width_decodes(self):
        # Both halves high-bit set: each INTEGER carries a leading zero, which
        # is the widest signature this encoder ever produces (141 bytes).
        raw = bytes([0xFF] * 66) + bytes([0xFF] * 66)
        der = self._decoded(raw)
        assert len(der) == 141
        assert der[:3] == b"\x30\x81\x8a"

    def test_unequal_r_and_s_widths_decode(self):
        # r small, s at full width: DER INTEGERs are minimal, so the two lengths
        # differ and a fixed-width assumption anywhere would break here.
        self._decoded(bytes(65) + bytes([0x07]) + bytes([0xFF] * 66))

    def test_a_p256_pair_still_uses_the_short_form(self):
        der = self._decoded(bytes([0xFF] * 32) + bytes([0x01] * 32))
        assert der[1] == len(der) - 2


class TestRawSignatureSize:
    """The placeholder the dry run reserves must hold the widest DER the same
    curve can produce, header growth included."""

    @staticmethod
    def _bound(bit_size: int) -> int:
        import types

        from engine.signatures import StoreSigner

        fake = types.SimpleNamespace(
            signing_cert=types.SimpleNamespace(
                public_key=types.SimpleNamespace(algorithm="ec", bit_size=bit_size)
            )
        )
        return StoreSigner._raw_signature_size(fake)

    @pytest.mark.parametrize("bit_size,expected", [(256, 72), (384, 104), (521, 141)])
    def test_the_bound_is_the_widest_der_for_the_curve(self, bit_size, expected):
        assert self._bound(bit_size) == expected

    @pytest.mark.parametrize("bit_size", [256, 384, 521])
    def test_the_widest_signature_actually_fits(self, bit_size):
        field = (bit_size + 7) // 8
        widest = wincert.ecdsa_der(bytes([0xFF] * field) * 2)
        assert len(widest) == self._bound(bit_size)
