import { resolve } from 'node:path';
import { existsSync, rmSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { tmpdir } from 'node:os';
import { expect } from '@wdio/globals';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — no type declarations for the deep legacy import
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import {
  waitForHarness,
  getState,
  getWorkspacePageIds,
  invokeAppCommand,
} from '../support/harness.js';

// Create PDF, through the REAL dialog and the REAL engine.
//
// What this proves that pytest cannot: the command opens the rewritten
// dialog, the dialog's own list model feeds the engine, and the result opens
// through the normal funnel. Native pickers are undrivable by WebDriver, so
// the harness injects the source LIST — the same `addPaths` the picker's
// result goes through, so an injected run and a clicked one cannot diverge.
//
// The three assertions:
//   * create-from-image is DPI-HONEST — a 300-dpi raster becomes a Letter
//     page, not a 25-inch one;
//   * create-from-docx is TEXT-EXTRACTABLE — the source's sentinel token
//     comes back out of the produced PDF;
//   * a blank page is a real page, in the position the list put it.

const require = createRequire(import.meta.url);
pdfjs.GlobalWorkerOptions.workerSrc = pathToFileURL(
  require.resolve('pdfjs-dist/legacy/build/pdf.worker.mjs'),
).href;

const DOCX_FIXTURE = resolve(__dirname, '..', '..', 'tests', 'fixtures', 'sources', 'report.docx');
const XLSX_FIXTURE = resolve(__dirname, '..', '..', 'tests', 'fixtures', 'sources', 'sheet.xlsx');
const FORM_FIXTURE = resolve(__dirname, '..', '..', 'tests', 'fixtures', 'form-pdflib.pdf');
const TOKEN = 'ZQXJ-2026';

interface CreatePdfRunResult {
  output: string;
  pages: number;
}

async function createPdfRun(
  sources: string[],
  output: string,
  options?: Record<string, unknown>,
): Promise<CreatePdfRunResult | null> {
  return browser.executeAsync<CreatePdfRunResult | null, [string[], string, unknown]>(
    function (srcs, out, opts, done) {
      (window as any).__SPECTRA_TEST__.createPdfRun(srcs, out, opts ?? undefined)
        .then((r: CreatePdfRunResult | null) => done(r))
        .catch(() => done(null));
    },
    sources,
    output,
    options ?? null,
  );
}

async function combineRun(
  sources: string[],
  output: string,
  options?: Record<string, unknown>,
): Promise<CreatePdfRunResult | null> {
  return browser.executeAsync<CreatePdfRunResult | null, [string[], string, unknown]>(
    function (srcs, out, opts, done) {
      (window as any).__SPECTRA_TEST__.combineRun(srcs, out, opts ?? undefined)
        .then((r: CreatePdfRunResult | null) => done(r))
        .catch(() => done(null));
    },
    sources,
    output,
    options ?? null,
  );
}

async function readPdf(
  path: string,
): Promise<{ pages: number; boxes: number[][]; text: string; fields: string[] }> {
  const pdf = await pdfjs.getDocument({
    data: new Uint8Array(readFileSync(path)),
  }).promise;
  const boxes: number[][] = [];
  let text = '';
  for (let i = 1; i <= pdf.numPages; i += 1) {
    const page = await pdf.getPage(i);
    const [, , width, height] = page.view as number[];
    boxes.push([Math.round(width), Math.round(height)]);
    const content = await page.getTextContent();
    text += (content.items as { str?: string }[]).map((item) => item.str ?? '').join(' ');
  }
  const pages = pdf.numPages;
  const fieldObjects = (await pdf.getFieldObjects()) as Record<string, unknown> | null;
  const fields = fieldObjects ? Object.keys(fieldObjects).sort() : [];
  await pdf.loadingTask.destroy();
  return { pages, boxes, text, fields };
}

/** A deterministic 300-dpi Letter-sized grayscale PNG, written by hand.
 *
 * Hand-built rather than generated by a library so the fixture's DPI is a
 * FACT of the bytes this test wrote: a pHYs chunk of 11811 pixels/metre is
 * exactly 300 dpi, and 2550x3300 of them is 8.5x11 inches. If the page comes
 * back 612x792 the wrap read that chunk; if it comes back 2550x3300 it did
 * not, which is the defect the DPI rule exists to prevent.
 */
function writeThreeHundredDpiPng(path: string): void {
  const width = 2550;
  const height = 3300;
  const crcTable: number[] = [];
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    crcTable[n] = c >>> 0;
  }
  const crc = (buf: Buffer): number => {
    let c = 0xffffffff;
    for (const byte of buf) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type: string, data: Buffer): Buffer => {
    const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const checksum = Buffer.alloc(4);
    checksum.writeUInt32BE(crc(body));
    return Buffer.concat([length, body, checksum]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 0; // grayscale
  const phys = Buffer.alloc(9);
  phys.writeUInt32BE(11811, 0); // px/metre == 300 dpi
  phys.writeUInt32BE(11811, 4);
  phys[8] = 1; // unit: metre
  const raw = Buffer.alloc((width + 1) * height, 0xe6);
  for (let y = 0; y < height; y += 1) raw[y * (width + 1)] = 0; // filter: none
  const idat = require('node:zlib').deflateSync(raw);
  writeFileSync(
    path,
    Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      chunk('IHDR', ihdr),
      chunk('pHYs', phys),
      chunk('IDAT', idat),
      chunk('IEND', Buffer.alloc(0)),
    ]),
  );
}

describe('Create PDF from any file', () => {
  let tmp: string;
  let pngPath: string;

  before(() => {
    tmp = mkdtempSync(resolve(tmpdir(), 'spectra-p22-'));
    pngPath = resolve(tmp, 'scan.png');
    writeThreeHundredDpiPng(pngPath);
  });

  after(() => {
    if (tmp && existsSync(tmp)) rmSync(tmp, { recursive: true, force: true });
  });

  it('builds one PDF from a document, an image and a blank page, in list order', async function () {
    this.timeout(180_000);
    await waitForHarness();

    // The command's own id — renamed from file.createPdfFromPostScript, which
    // no longer exists anywhere.
    expect(await invokeAppCommand('file.createPdf')).toBe(true);
    await $('[data-testid="create-pdf-dialog"]').waitForDisplayed({ timeout: 10_000 });

    const outPath = resolve(tmp, 'mixed.pdf');
    const result = await createPdfRun([DOCX_FIXTURE, pngPath, '__blank__'], outPath);
    expect(result).not.toBe(null);
    expect(result!.pages).toBe(3);
    await $('[data-testid="create-pdf-done"]').waitForDisplayed({ timeout: 30_000 });

    // The list rendered a row per source, badged by kind.
    const kinds = await $$('[data-testid="create-pdf-row"]').map((row) =>
      row.getAttribute('data-kind'),
    );
    expect(kinds).toEqual(['office', 'image', 'blank']);

    // Node-side, independent of the app: the output is what it claims.
    expect(existsSync(outPath)).toBe(true);
    const pdf = await readPdf(outPath);
    expect(pdf.pages).toBe(3);
    // create-from-docx: real extractable text, not a page image.
    expect(pdf.text).toContain(TOKEN);
    // create-from-image: DPI-HONEST. 2550x3300 px at 300 dpi is 612x792 pt.
    expect(pdf.boxes[1]).toEqual([612, 792]);
    // the blank page is a real page at the size the builder gives it.
    expect(pdf.boxes[2]).toEqual([612, 792]);

    // The Open action routes through the normal funnel.
    await $('[data-testid="create-pdf-open"]').click();
    await browser.waitUntil(
      async () => ((await getState()).activeFile?.path ?? '').includes('mixed.pdf'),
      { timeout: 20_000, timeoutMsg: 'the created PDF never opened in the app' },
    );
  });

  it('normalises every page onto a chosen size without stretching', async function () {
    this.timeout(180_000);
    expect(await invokeAppCommand('file.createPdf')).toBe(true);
    await $('[data-testid="create-pdf-dialog"]').waitForDisplayed({ timeout: 10_000 });

    const outPath = resolve(tmp, 'a4.pdf');
    const result = await createPdfRun([XLSX_FIXTURE, pngPath], outPath, {
      pageSize: 'a4',
      orientation: 'auto',
      marginPt: 18,
    });
    expect(result).not.toBe(null);
    await $('[data-testid="create-pdf-done"]').waitForDisplayed({ timeout: 30_000 });

    const pdf = await readPdf(outPath);
    expect(pdf.pages).toBe(2);
    for (const box of pdf.boxes) expect(box).toEqual([595, 842]);
    // Sizing must not cost the text: the spreadsheet's token survives.
    expect(pdf.text).toContain(TOKEN);

    await $('[data-testid="create-pdf-close"]').click();
    await $('[data-testid="create-pdf-dialog"]').waitForDisplayed({
      reverse: true,
      timeout: 10_000,
    });
  });

  it('refuses a source no arm converts, in the dialog, before any conversion', async function () {
    this.timeout(120_000);
    expect(await invokeAppCommand('file.createPdf')).toBe(true);
    await $('[data-testid="create-pdf-dialog"]').waitForDisplayed({ timeout: 10_000 });

    const bogus = resolve(tmp, 'thing.zip');
    writeFileSync(bogus, Buffer.from('PK\u0003\u0004not a document'));
    const outPath = resolve(tmp, 'never.pdf');
    const result = await createPdfRun([bogus], outPath);
    expect(result).toBe(null);
    // The row is badged as unsupported and the Convert button is disabled —
    // a refused source is never silent.
    await $('[data-testid="create-pdf-unsupported"]').waitForDisplayed({ timeout: 10_000 });
    expect(await $('[data-testid="create-pdf-convert"]').isEnabled()).toBe(false);
    expect(existsSync(outPath)).toBe(false);

    await $('[data-testid="create-pdf-close"]').click();
    await $('[data-testid="create-pdf-dialog"]').waitForDisplayed({
      reverse: true,
      timeout: 10_000,
    });
  });

  // ── Combine Files, widened ──────────────────────────────────────────────
  //
  // Combine took PDFs only, because a .docx cannot enter the page tier. The
  // journey proved here is the whole widening: a mixed list — a form-bearing
  // PDF, a page RANGE of another PDF, and a spreadsheet — becomes one
  // document with the form's fields intact, and then a further source is
  // added into a document that is already open.

  it('combines a mixed list into one new document, keeping form fields', async function () {
    this.timeout(240_000);
    expect(await invokeAppCommand('document.combineFiles')).toBe(true);
    await $('[data-testid="combine-dialog"]').waitForDisplayed({ timeout: 10_000 });

    const outPath = resolve(tmp, 'combined.pdf');
    // mixed.pdf (3 pages, built above) contributes only pages 2-3.
    const result = await combineRun(
      [FORM_FIXTURE, resolve(tmp, 'mixed.pdf'), XLSX_FIXTURE],
      outPath,
      { target: 'new', ranges: [null, '2-3', null] },
    );
    expect(result).not.toBe(null);
    await $('[data-testid="combine-done"]').waitForDisplayed({ timeout: 60_000 });

    // Every row is badged by kind and by the converter it will use.
    const kinds = await $$('[data-testid="combine-row"]').map((row) =>
      row.getAttribute('data-kind'),
    );
    expect(kinds).toEqual(['pdf', 'pdf', 'office']);
    const states = await $$('[data-testid="combine-row"]').map((row) =>
      row.getAttribute('data-state'),
    );
    expect(states).toEqual(['ready', 'ready', 'ready']);

    const form = await readPdf(FORM_FIXTURE);
    const pdf = await readPdf(outPath);
    expect(pdf.pages).toBe(form.pages + 2 + 1);
    // The spreadsheet really converted — its sentinel token comes back out.
    expect(pdf.text).toContain(TOKEN);
    // The standing risk: assembly goes through the SHIPPED
    // merge, so the form member's fields are still registered and fillable.
    expect(form.fields.length).toBeGreaterThan(0);
    expect(pdf.fields).toEqual(form.fields);

    await $('[data-testid="combine-close"]').click();
    await $('[data-testid="combine-dialog"]').waitForDisplayed({
      reverse: true,
      timeout: 10_000,
    });
  });

  it('adds converted pages into a document that is already open', async function () {
    this.timeout(240_000);
    // mixed.pdf was opened through the funnel by the first test.
    expect((await getState()).activeFile?.path ?? '').toContain('mixed.pdf');
    const before = await getWorkspacePageIds();
    expect(before.length).toBe(3);

    expect(await invokeAppCommand('document.combineFiles')).toBe(true);
    await $('[data-testid="combine-dialog"]').waitForDisplayed({ timeout: 10_000 });
    // The open document is offered as a destination and preselected.
    expect(await $('[data-testid="combine-destination"]').isDisplayed()).toBe(true);

    const result = await combineRun([XLSX_FIXTURE], '', { target: 'append' });
    expect(result).not.toBe(null);
    expect(result!.pages).toBe(1);
    await $('[data-testid="combine-appended"]').waitForDisplayed({ timeout: 60_000 });

    // The pages entered the PAGE TIER — undoable page-tier work, the same
    // machinery Insert Pages uses, with no new commit path.
    await browser.waitUntil(async () => (await getWorkspacePageIds()).length === 4, {
      timeout: 30_000,
      timeoutMsg: 'the converted spreadsheet never reached the open document',
    });

    await $('[data-testid="combine-close"]').click();
    await $('[data-testid="combine-dialog"]').waitForDisplayed({
      reverse: true,
      timeout: 10_000,
    });
  });

  it('refuses a bad page range in the dialog, before any conversion', async function () {
    this.timeout(120_000);
    expect(await invokeAppCommand('document.combineFiles')).toBe(true);
    await $('[data-testid="combine-dialog"]').waitForDisplayed({ timeout: 10_000 });

    const outPath = resolve(tmp, 'never-combined.pdf');
    const result = await combineRun([resolve(tmp, 'mixed.pdf')], outPath, {
      target: 'new',
      ranges: ['1-'],
    });
    expect(result).toBe(null);
    await $('[data-testid="combine-blocked"]').waitForDisplayed({ timeout: 10_000 });
    expect(await $('[data-testid="combine-run"]').isEnabled()).toBe(false);
    expect(existsSync(outPath)).toBe(false);

    await $('[data-testid="combine-close"]').click();
    await $('[data-testid="combine-dialog"]').waitForDisplayed({
      reverse: true,
      timeout: 10_000,
    });
  });
});
