# scripts/vendor-linux-wheels.sh
#!/usr/bin/env bash
# Populates vendor/wheels-linux/ + scripts/vendored-wheels-linux.tsv from
# scripts/python-requirements.txt, so debian/postinst can install every
# dependency with `pip install --no-index` on a machine with no network.
#
# Run this manually whenever python-requirements.txt changes, then commit
# vendor/wheels-linux/ and the regenerated manifest. Needs network + a
# manylinux-compatible Python (matching your minimum supported version).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$SCRIPT_DIR/.."
LOCK_FILE="$SCRIPT_DIR/python-requirements.txt"
DEST="$ROOT/vendor/wheels-linux"
MANIFEST="$SCRIPT_DIR/vendored-wheels-linux.tsv"

rm -rf "$DEST"
mkdir -p "$DEST"

TEMP_REQ=$(mktemp)
sed -E 's/ --hash=sha256:[a-f0-9]+//g' "$LOCK_FILE" > "$TEMP_REQ"

echo "Downloading Linux wheels for all deps in $LOCK_FILE..."
pip download -r "$TEMP_REQ" --dest "$DEST" \
    --only-binary=:all:
rm -f "$TEMP_REQ"

{
    echo "# Auto-generated by scripts/vendor-linux-wheels.sh -- do not hand-edit."
    echo "file	sha256"
    for f in "$DEST"/*.whl; do
        sha=$(sha256sum "$f" | awk '{print $1}')
        echo "$(basename "$f")	$sha"
    done
} > "$MANIFEST"

echo "Done. $(ls "$DEST"/*.whl | wc -l) wheel(s) staged in $DEST"
echo "Review as a git diff, then commit vendor/wheels-linux/ and $MANIFEST."